BEGIN TRANSACTION;

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "description" text,
  "price" money,
  "location" varchar(15),
  "registered_course_id" int,
  "teachers" text
);

INSERT INTO courses (description, name, price, location, registered_course_id, teachers) VALUES ('lorem', 'ipsum', 20.00, 'Auckland', 1, 'Mr.John-Smith');


COMMIT;